name: freeenergy
owner: chemteam
description: "Free energy tools of BRIDGE."
remote_repository_url: https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/tools/free_energy
type: unrestricted
categories:
- Molecular Dynamics
- Computational chemistry
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the freeenergy package: {{ tool_name }}"
maintainers:
  - tsenapathi
  - chrisbarnettster